### PR TITLE
feat: add support for semesters

### LINKED ISSUE #7: Support semesterisation
Brought up in #6 

> From **September 2023**, the University academic year will be split into two semesters and for the majority of courses this will replace our current three term model.[^1]

Since Semesters require different string formatting (`Semester _`) to terms (`_ Term`), they should probably be a separate class. Potentially some form of StudyPeriod should directly subclass Period, from which Semester and Term can both subclass. 

[^1]: https://www.york.ac.uk/about/term-dates/

### PR DESCRIPTION
**Pull request by chriscn**
As described in #7, this PR will add support for semesterisation. Currently is a crude implementation in that it just has a large list of what each week means. I to intend to write some software to query this and provide it with a Calendar link as I have a feeling the current ones will break.

### CODE REVIEW

**Comment by chriscn** [comment]
@LukeMoll this is ready to merge now. If you'd like to request any changes let me know and I'll implement then.

**Comment by LukeMoll** [comment]
Thanks for getting the ball rolling on this! I do appreciate it as I hadn't seen the format of semesterisation yet.

I think there will be some changes needed, I'll outline them below

## Separate `Semester` and `Holiday` objects
Conceptually I'd like to keep one object per period; if there are two semesters then they should be represented with two objects. Similarly, the Christmas, Easter, and Summer breaks should be represented with `Holiday` objects rather than baked into the Semester.

## Movable vacation/holiday period
I'm not a current UoY student (and I don't envy the change in pacing for those who'll be studying under semesterisation) but someone was kind enough to send me a copy of the spreadsheet you linked in #7 .
image
As you can see, Easter vacation moves to accomodate Easter Sunday, so the location of the vacation within Semester 2 can't be hard-coded.

Instead, I think the core should to be reworked so that Periods have a start **and end** date. Holiday can sit within a Semester and take precedence, so that if a date is within both a Semester and a Holiday, then the reported Period is the Holiday. 
If end dates were made exclusive, then this would be easier to back-port to the existing Terms. 

Alternatively, the existing structure could be re-used and add the concept of "resumable" Semester 2, which might look like this:
```
Semester(date(2023,9,18), 1)
Holiday(date(2023,12,18), "Christmas")
Semester(date(2024,2,5), 2)
Holiday(date(2024,3,25), "Easter")
Semester(date(2024,4,8, 2, resumefrom=7)
Holiday(date(2024,6,7), "Summer")
```
Then the counting inside that Semester object has an offset applied.

## Programmatic week counting
It would be nice to perform the counting in code, rather than a long look-up table. A series of if statements could encode the same information more compactly and in an easier format to make changes to. Formatting options are less urgent, for now the style could be kept similar to the Term-based naming. "Week" can also be dropped imo. For example:
```
Semester 1/Freshers
Semester 1/Teaching 1
...
Semester 1/Consolidation
...
Christmas/1
...
Semester 1/Revision
Semester 1/Assessment 1
```

---

I realise this is more than a few minor tweaks, please let me know what you think of them. I want to emphasise that even with these changes requested, this is a really useful contribution and I appreciate your hard work on it!

**Comment by chriscn** [comment]
I thank your input, doing things progamatically is always better, I thankfully only have one year in this system before I leave. I'll work through a solution over the next couple of days and try and get some code together.

**Comment by chriscn** [comment]
Would like to hear your thoughts on a solution I've been thinking about over the last couple of days.

```
SemesterOne(Period), and SemesterTwo(Period)
```
The only thing that moves in Easter, so with SemesterTwo you construct it with the Monday of the first easter holiday week. It will then work everything else around that?

**Comment by chriscn** [comment]
I'm going to close this in favour of my [Calendar](https://calendar.chrisnethercott.co.uk/).

**Pull request closed without merging**
